apiVersion: v1
kind: Service
metadata:
  name: image-service-load-test
  labels:
    app: load-test-web-trigger
    tier: web
spec:
  selector:
    app: load-test-web-trigger
  ports:
    - port: 8780

---

apiVersion: v1
kind: ReplicationController
metadata:
 name: image-service-load-test
spec:
  replicas: 1
  template:
      metadata:
        name: image-service-load-test
        labels:
          app: load-test-web-trigger
      spec:
       containers:
       - name: image-service-load-test
         image: sayenpl/load-test
         resources:
            requests:
              cpu: 500m
              memory: 1Gi

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-test-1
spec:
  backend:
    serviceName: image-service-load-test
    servicePort: 8780

