apiVersion: v1
kind: Service
metadata:
  name: image-service-load-test
  labels:
    app: load-test-web-trigger
    tier: web
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31111
  selector:
      name: image-service-load-test

---

apiVersion: v1
kind: ReplicationController
metadata:
 name: image-service-load-test
spec:
  replicas: 1
  template:
      metadata:
        name: image-service-load-test
        labels:
          app: load-test-web-trigger
      spec:
       containers:
       - name: image-service-load-test
         image: sayenpl/load-test
         resources:
            requests:
              cpu: 500m
              memory: 1Gi
         ports:
         - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-test-1
spec:
  backend:
    serviceName: image-service-load-test
    servicePort: 8080

